create table "public"."products_history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "asin" text not null,
    "final_price" double precision not null
);


alter table "public"."products_history" enable row level security;

CREATE UNIQUE INDEX products_history_pkey ON public.products_history USING btree (id);

alter table "public"."products_history" add constraint "products_history_pkey" PRIMARY KEY using index "products_history_pkey";

alter table "public"."products_history" add constraint "products_history_asin_fkey" FOREIGN KEY (asin) REFERENCES products(asin) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."products_history" validate constraint "products_history_asin_fkey";

grant delete on table "public"."products_history" to "anon";

grant insert on table "public"."products_history" to "anon";

grant references on table "public"."products_history" to "anon";

grant select on table "public"."products_history" to "anon";

grant trigger on table "public"."products_history" to "anon";

grant truncate on table "public"."products_history" to "anon";

grant update on table "public"."products_history" to "anon";

grant delete on table "public"."products_history" to "authenticated";

grant insert on table "public"."products_history" to "authenticated";

grant references on table "public"."products_history" to "authenticated";

grant select on table "public"."products_history" to "authenticated";

grant trigger on table "public"."products_history" to "authenticated";

grant truncate on table "public"."products_history" to "authenticated";

grant update on table "public"."products_history" to "authenticated";

grant delete on table "public"."products_history" to "service_role";

grant insert on table "public"."products_history" to "service_role";

grant references on table "public"."products_history" to "service_role";

grant select on table "public"."products_history" to "service_role";

grant trigger on table "public"."products_history" to "service_role";

grant truncate on table "public"."products_history" to "service_role";

grant update on table "public"."products_history" to "service_role";


